=== tibisay/pysafet/pysafet/media/templates/doc/yawlworkflow.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : yawlworkflow.dtd
    Created on : 22 de enero de 2008, 15:46
    Author     : vbravo
    Description:
        Una definicion para gestionar archivos de flujos de trabajo (workflow)
        con el lenguaje YAWL (Yet Another Workflow Language) 
        http://www.yawl-system.com dentro del proyecto SAFET :
        Sistema Automatizado para Firma Electronica y Estampillado de Tiempo

    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/yawlworkflow.dtd
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT yawl (workflow,configuration+)>
<!ATTLIST yawl
version  CDATA #REQUIRED> <!-- must be "0.01"> -->
<!ELEMENT workflow ((task|compositetask|variable|condition)*,token)>
<!ELEMENT token (#PCDATA) >
<!ATTLIST token     key CDATA #REQUIRED                    
                    description CDATA #IMPLIED
                    type (sql|file|webpage) "sql"
                    config CDATA #IMPLIED
                    keysource CDATA #REQUIRED>
<!ELEMENT configuration (#PCDATA) >
<!ATTLIST configuration  id CDATA #REQUIRED
                         connectstring CDATA #REQUIRED>
<!ATTLIST workflow  id CDATA #REQUIRED
                    desc CDATA #IMPLIED>
<!ELEMENT task (variable|port|autofilter)*>
<!ATTLIST task id CDATA #REQUIRED 
               title  CDATA #IMPLIED
               multiplicity (unique|multiple) "unique"
          type (atomic|composite) "atomic"
          report (yes|no) "no"  >
<!ELEMENT compositetask (workflow)>
<!ELEMENT variable (document*)>
<!ATTLIST variable  id CDATA #REQUIRED 
                    tokenlink CDATA #IMPLIED
                    description CDATA #IMPLIED
                    scope (net|task) "net"
                    type (sql|file|webpage) "sql"
                    usage (input|output|inout) "input"
                    config CDATA #IMPLIED
                    source CDATA #IMPLIED
                    documentsource CDATA #REQUIRED>
<!ELEMENT document (#PCDATA)  >
<!ATTLIST document  key CDATA #REQUIRED>
<!ELEMENT connection (#PCDATA) >
<!ATTLIST connection source  CDATA #IMPLIED
		     query CDATA #IMPLIED
		     options CDATA #IMPLIED
		     tokenlink CDATA #IMPLIED>					 
<!ELEMENT port (connection+) >
<!ELEMENT autofilter (#PCDATA) >
<!ATTLIST autofilter id CDATA #REQUIRED 
		side (bottom|down|up|forward) "forward"
	       source  CDATA #REQUIRED
               type (join|split)  #REQUIRED
               query  CDATA #REQUIRED
               options  CDATA #IMPLIED		
               tokenlink  CDATA #IMPLIED
               pattern (none|and|or|xor) "or"
               report (yes|no) "no"  >
<!ATTLIST port side (bottom|down|up|forward) #REQUIRED
               type (join|split)  #REQUIRED
               query  CDATA #IMPLIED
               tokenlink  CDATA #IMPLIED
               options  CDATA #IMPLIED
               drop    CDATA #IMPLIED  
	       config CDATA #IMPLIED
               pattern (none|and|or|xor) "none">
<!ELEMENT condition (port+) >
<!ATTLIST condition id CDATA #REQUIRED
                    type (start|end|inprocess) "inprocess"
            report (yes|no) "no"  >
<!ELEMENT taskid (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT connectstring (#PCDATA)>
<!ELEMENT parameter (#PCDATA)>

=== tibisay/pysafet/pysafet/PySafet/safetexample7v2.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--
    Document   : safetexample3.xml
    Created on : 23 de enero de 2008, 9:39
    Author     : vbravo
    Description:
        Purpose of the document follows.
-->
<!DOCTYPE yawl SYSTEM "http://trac-safet.cenditel.gob.ve/dtd/yawlworkflow.dtd">
<!--
    Agregar un elemento token, que defina la definición del token en cada
    uno de las actividades (tasks) o condiciones (condition)
    por ejemplo:
    fieldtoken, fieldrelation
-->

<yawl  version="0.01">
<workflow id="Flujo Principal de la Solicitud de Pago" desc="alguna descripcion">
    <condition id="inicial" type="start">
        <port side="forward" type="split" >
        <connection  source="Factura" query="select proveedor_ingreso FROM proveedor" options="&lt;2008-07-16" >            
        </connection>
        </port>
    </condition>    
    <task id="Factura" title="Tarea para datos de la Factura">
	    <port side="forward" type="split"   pattern="and">
		    <connection  source="Gerencia" tokenlink="[solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" 
		   query="select solicitud_tipo from solicitud"
		  options="gerencia">
		    </connection>
		    <connection  source="Presupuesto" tokenlink="[solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" 
		   query="select solicitud_tipo from solicitud"
		  options="presupuesto">
		    </connection>
	    </port>
	    <variable id="Facturas" scope="task"  type="sql" config="1" 
		      tokenlink="[factura_cedulaproveedor]" documentsource="SELECT proveedor_cedula,apellidos,factura_numero,proveedor_ingreso from factura">
	    </variable> 
    </task>
    <task id="Gerencia" title="Tarea para la solicitud del Recurso Humano">
	    <port side="forward" type="split"  >
		    <connection  source="Pago" tokenlink="[solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" 
		  query="select solicitud_gerencia from solicitud" options="true">
		    </connection>
	    </port>
	    <variable id="Gerencias" scope="task"  type="sql" config="1" source="Cheque" 
		      tokenlink="[solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" documentsource="SELECT apellidos,nombres,proveedor_ingreso from solicitud where solicitud_tipo='gerencia'">
	    </variable>
    </task>
    <task id="Presupuesto" title="Tarea para la solicitud del Almacen">
	    <port side="forward" type="split" pattern="or" >
		    <connection  source="Corriente" tokenlink="[presupuesto_id:presupuesto,solicitud_presupuestotipo:solicitud][solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" 
		  query="select presupuesto_tipo from presupuesto" options="corriente:alterno">
		    </connection>
		    <connection  source="Alterno" tokenlink="[presupuesto_id:presupuesto,solicitud_presupuestotipo:solicitud][solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" 
		  query="select presupuesto_tipo from presupuesto" options="corriente:alterno">
		    </connection>
	    </port>
	    <variable id="Presupuestos" scope="task"  type="sql" config="1" source="Cheque" 
		      tokenlink="[solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" documentsource="SELECT solicitud_numero,solicitud_consignado from solicitud where solicitud_tipo='presupuesto'">
	    </variable>
    </task>
    <task id="Corriente" title="Tarea para la solicitud del Presupuesto Corriente">
	    <port side="forward" type="split" >
		    <connection  source="Pago" tokenlink="[solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" 
		  query="select solicitud_presupuesto from solicitud" options="true">
		    </connection>
	    </port>
	    <variable id="Corrientes" scope="task"  type="sql" config="1" source="Cheque" 
		      tokenlink="[solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" documentsource="SELECT solicitud_numero,solicitud_consignado from solicitud where solicitud_tipo='presupuesto'">
	    </variable>
    </task>
    <task id="Alterno" title="Tarea para la solicitud del Presupuesto Alterno">
	    <port side="forward" type="split" >
		    <connection  source="Pago" tokenlink="[solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" 
		  query="select solicitud_presupuesto from solicitud" options="true">
		    </connection>
	    </port>
	    <variable id="Alternos" scope="task"  type="sql" config="1" source="Cheque" 
		      tokenlink="[solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" documentsource="SELECT solicitud_numero,solicitud_consignado from solicitud where solicitud_tipo='presupuesto'">
	    </variable>
    </task>
    <task id="Pago" title="Tarea donde se emitió el cheque">
	    <port side="forward" type="split" >
		    <connection  source="final" query="true">
		    </connection>
	    </port>
	    <variable id="Pagos" scope="task"  type="sql" config="1"  source="end"
		      tokenlink="[cheque_numero,numero_cheque:solicitudcheque][numero_solicitud,solicitud_numero:solicitud][solicitud_numerofactura,factura_numero:factura][factura_cedulaproveedor]" documentsource="SELECT proveedor_cedula,apellidos,nombres,cheque_numero,cheque_monto,fecha FROM cheque" >
	    </variable>
    </task>
    <condition id="final" type="end">
	    <port side="forward" type="split">
		    <connection  source="">            
		    </connection>
	    </port>
    </condition>    
    <token key="proveedor_cedula"  keysource="proveedor">    
    </token>
</workflow>
<configuration id="1" connectstring="psql:localhost:pagos:vbravo:vbravo_">
</configuration>
</yawl>

=== tibisay/pysafet/pysafet/apps/httpexample/cartelerafirmada.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : tickets.xml
Creado     : 16/10/08 09:27 AM
Autor      : nombre_autor
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->

<!--<!DOCTYPE yawl SYSTEM "http://trac-safet.cenditel.gob.ve/dtd/yawlworkflow.dtd">-->
<!DOCTYPE yawl SYSTEM "file:///home/vbravo/.safet/dtd/yawlworkflow.dtd">
<yawl  version="0.01">
<workflow id="Tickets" desc="Tickets usados por Trac">
	<token key="id"  keysource="ticket">
	</token>
	<parameter type="combolisttable" icon="hito.png" desc= "By Project" mandatory="no" options="projectId:projects::title"  
	  title="ByProject" defaultvalue="0">
	</parameter>	
 <parameter title="Direccion_Grafico_de_Flujo" options="TB::La direccin del grfico es arriba-abajo::TB,LR::La direccin del grfico es izquierda-derecha::LR" configurekey="Plugins.Graphviz/plugins.graphviz.graph.rankdir" type="combolistliteral" mandatory="no" />

<condition id="inicial" type="start">
                <port side="forward" type="split"   >
                        <connection   source="Project" query="select projectId from ticket"  options="{#ByProject}" tokenlink="">
			</connection>
		</port>
	</condition>
	<task id="Project"  title="{#ByProject}" report="no">
                <port side="forward" type="split" >
                        <connection source="ToDo" query="select status from ticket" options="ToDo" >
			</connection>
		</port>
		<variable id="vProject" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select summary as resumen,description as descripcion,type as tipo,milestone as hito,owner as propietario from ticket" rolfield="owner" timestampfield="changetime">
		</variable>
	</task>
	
	<task id="ToDo"  title="New Tickets" report="yes" >
                <port side="forward" type="split" pattern="or">
                        <connection source="Progress" query="select status from ticket" options="Progress" >
			</connection>
                        <connection source="Postponed" query="select status from ticket" options="Postponed" >
			</connection>

		</port>
		<variable id="vToDo" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select status,resumen from vticket" rolfield="owner" timestampfield="changetime">
		</variable>
	</task>
	<task id="Progress"  title="inprogress" report="yes" >
                <port side="forward" type="split" pattern="or">
                        <connection source="Finished" query="select status from ticket"  options="Finished" >
			</connection>
	        <connection source="Postponed" query="select status from ticket" options="Postponed" >
			</connection>
		</port>
		<variable id="vProgress" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select status,resumen from vticket" >
		</variable>
	</task>
<task id="Postponed"  title="pospuestos" report="yes" >
                <port side="forward" type="split" >
                        <connection source="Finished" query="select status from ticket"  options="Finished" >
			</connection>
		</port>
		<variable id="vPostponed" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select status,resumen from vticket" >
		</variable>
	</task>
	<task id="Finished"  title="doit" report="yes">
                <port side="forward" type="split" >
                        <connection source="TicketSigned" query="vFinished  SIGN Antonio Araujo Brett" options="yes" >
			</connection>
		</port>
		<variable id="vFinished" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select status,resumen from vticket" rolfield="owner" timestampfield="changetime">
		</variable>
	</task>
	<task id="TicketSigned"  title="doit" report="yes">
                <port side="forward" type="split" >
                        <connection source="final" query="true" options="" >
			</connection>
		</port>
		<variable id="vTicketSigned" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select status,resumen from vticket" rolfield="owner" timestampfield="changetime">
		</variable>
	</task>

	<condition id="final">
		<port side="forward" type="split">
			<connection source="">
			</connection>
		</port>
	</condition>
</workflow>
	<configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_">
	</configuration>
</yawl>

=== tibisay/pysafet/pysafet/PySafet/flujoviaticosgeneral.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : tickets.xml
Creado     : 16/10/08 09:27 AM
Autor      : nombre_autor
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->

<!--<!DOCTYPE yawl SYSTEM "http://trac-safet.cenditel.gob.ve/dtd/yawlworkflow.dtd">-->
<!DOCTYPE yawl SYSTEM "file:///home/vbravo/PySafet/yawlworkflow.dtd">
<yawl  version="0.01">
<workflow id="Viaticos" desc="Flujo de planillas de viaticos">
	<token key="viaticos.id"  keysource="viaticos">
	</token>
<condition id="inicial" type="start">
                <port side="forward" type="split"   >
                        <connection   source="Solicitado" query="select status from personal"  options="solicitado" tokenlink="[cedula,cedulaviajero:viaticos]">
			</connection>
		</port>
	</condition>
	<task id="Solicitado"  title="en_evaluacion" >
                <port side="forward" type="split"   >
                        <connection source="Director" query="VariableSolicitado SIGN Antonio Araujo Brett;Victor Bravo" options="" tokenlink="[cedula,cedulaviajero:viaticos]">
			</connection>
</port>
		<variable id="VariableSolicitado" scope="task"  type="sql" config="1"   tokenlink="[cedula,cedulaviajero:viaticos]" documentsource="select id,nombres,apellidos,horasalida,horallegada,proyecto,ciudad from personal" >
		</variable>
	</task>
	<task id="Director"  title="aaraujo" >
                <port side="forward" type="split" >
                        <connection source="Presupuesto" query="VariableSolicitado SIGN Victor Bravo,Antonio Araujo Brett" options="" tokenlink="[cedula,cedulaviajero:viaticos]">
			</connection>
		</port>
		<variable id="VariableDirector" scope="task"  type="sql" config="1"   tokenlink="[cedula,cedulaviajero:viaticos]" documentsource="select id,cedula,nombres,apellidos,horasalida,horallegada,proyecto,ciudad,fechasolicitud,fechadirector,fechadirector-fechasolicitud as Espera from personal" >
		</variable>
<autofilter id="PorEmpleado" type="split" source="Presupuesto" query="select cedulaviajero from viaticos" tokenlink="[cedula,cedulaviajero:viaticos]" report="yes"> 
</autofilter>
	</task>
	<task id="Presupuesto"  title="vbravo" >
                <port side="forward" type="split" >
                        <connection source="Presidente" query="VariableSolicitado SIGN Victor Bravo,Antonio Araujo Brett,Leandro Leon" options="" tokenlink="[cedula,cedulaviajero:viaticos]">
			</connection>
		</port>
		<variable id="VariablePresupuesto" scope="task"  type="sql" config="1"   tokenlink="[cedula,cedulaviajero:viaticos]" documentsource="select id,cedula,nombres,apellidos,horasalida,horallegada,proyecto,ciudad,fechadirector,fechapresupuesto,fechapresupuesto-fechadirector as Espera from personal" >
		</variable>
	</task>
	<task id="Presidente"  title="lleon" >
                <port side="forward" type="split" >
                        <connection source="final" query="true" options="" >
			</connection>
		</port>
		<variable id="VariablePresidente" scope="task"  type="sql" config="1"   tokenlink="[cedula,cedulaviajero:viaticos]" documentsource="select id,cedula,nombres,apellidos,horasalida,horallegada,proyecto,ciudad from personal" >
		</variable>
	</task>

	<condition id="final">
		<port side="forward" type="split">
			<connection source="">
			</connection>
		</port>
	</condition>
</workflow>
	<configuration id="1" connectstring="psql:seguridad.cenditel.gob.ve:ticket:vbravo:vbravo_">
	</configuration>
</yawl>

=== tibisay/pysafet/pysafet/PySafet/tiquetesv3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
Documento  : tickets.xml
Creado     : 16/10/08 09:27 AM
Autor      : nombre_autor
Descripcion: Archivo generado por plantilla de la Libreria SAFET
-->

<!DOCTYPE yawl SYSTEM "http://trac-safet.cenditel.gob.ve/dtd/yawlworkflow.dtd">
<!--<!DOCTYPE yawl SYSTEM "file:///home/vbravo/trac/seguridad/safet/libsafet/trunk/doc/yawlworkflow.dtd">-->
<yawl  version="0.01">
<workflow id="NuevoFlujo" desc="Nuevo Flujo">
	<condition id="inicial" type="start">
                <port side="forward" type="split"  >
                        <connection   source="Nuevo" query="select estado from lista"  options="nuevo" tokenlink="">
			</connection>
		</port>
	</condition>
	<task id="Nuevo"  title="Tarea1">
                <port side="forward" type="split"  >
                        <connection source="Asignado" query="select estado from lista" options="asignado" >
			</connection>
		</port>
		<variable id="VariableNuevo" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select titulo,estado,asignado,propietario from lista" >
		</variable>
	</task>
	<task id="Asignado"  title="Tarea1">
                <port side="forward" type="split" pattern="or">
                        <connection source="Resuelto" query="select estado from lista" options="resuelto" >
			</connection>
                        <connection source="Pospuesto" query="select estado from lista" options="pospuesto" >
			</connection>
		</port>
		<variable id="VariableAsignado" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select titulo,estado,asignado,propietario from lista" >
		</variable>
	</task>
	<task id="Resuelto"  title="Tarea1">
                <port side="forward" type="split" >
			<connection source="FirmaResuelto" query="select id,titulo,estado,asignado,propietario from lista SIGN Victor Bravo" tokenlink="">
			</connection>
		</port>
		<variable id="VariableResuelto" scope="task"  type="sql" config="1"   tokenlink="" documentsource="select id,titulo,estado,asignado,propietario from lista" >
		</variable>
	</task>
	<task id="Pospuesto"  title="Tarea1">
		<port side="forward" type="split" query="select id,titulo,estado,asignado,propietario from lista SIGN Victor Bravo">
			<connection source="FirmaPospuesto">
			</connection>
		</port>
		<variable id="VariablePospuesto" scope="task"  type="sql" config="1"  tokenlink="" documentsource="select  id,titulo,estado,asignado,propietario from lista" >
		</variable>
	</task>
	<task id="FirmaResuelto"  title="Tarea1">
		<port side="forward" type="split" query="true">
                        <connection source="Finalizado">
			</connection>
		</port>
		<variable id="VariableFirmaResuelto" scope="task"  type="sql" config="1"  tokenlink="" documentsource="select titulo,estado,asignado,propietario from lista" >
		</variable>
	</task>
	<task id="FirmaPospuesto"  title="Tarea1">
		<port side="forward" type="split" query="true">
                        <connection source="Finalizado">
			</connection>
		</port>
		<variable id="VariableFirmaPospuesto" scope="task"  type="sql" config="1"  tokenlink="" documentsource="select titulo,estado,asignado,propietario from lista" >
		</variable>
        </task>
        <task id="Finalizado"  title="Tarea1">
                <port side="forward" type="split" >
                        <connection source="Calificado"  query="select estado from lista"  options="calificado" tokenlink="" >
                        </connection>
                </port>
                <variable id="VariableFinalizado" scope="task"  type="sql" config="1"  tokenlink="" documentsource="select titulo,estado,asignado,propietario from lista" >
                </variable>
        </task>
           <task id="Calificado"  title="Tarea1">
                <port side="forward" type="split" query="true">
                        <connection source="final" >
                        </connection>
                </port>
                <variable id="VariableCalificado" scope="task"  type="sql" config="1"  tokenlink="" documentsource="select titulo,estado,asignado,propietario from lista" >
                </variable>
        </task>
	<condition id="final">
		<port side="forward" type="split">
			<connection source="">
			</connection>
		</port>
	</condition>
	<token key="id"  keysource="lista">
	</token>
</workflow>
	<configuration id="1" connectstring="psql:localhost:tiquetes:vbravo:vbravo_">
	</configuration>
</yawl>
